// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: job_descriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobDescriptionSQL = `-- name: CreateJobDescriptionSQL :one
INSERT INTO job_descriptions (application_id, raw_text, extracted_keywords, ai_summary)
VALUES (
    $1::uuid,
    $2,
    COALESCE($3, '{}'),
    $4
)
RETURNING id::text, application_id::text, raw_text, extracted_keywords, ai_summary, created_at, updated_at
`

type CreateJobDescriptionSQLParams struct {
	ApplicationID     string      `json:"application_id"`
	RawText           string      `json:"raw_text"`
	ExtractedKeywords interface{} `json:"extracted_keywords"`
	AiSummary         *string     `json:"ai_summary"`
}

type CreateJobDescriptionSQLRow struct {
	ID                string             `json:"id"`
	ApplicationID     string             `json:"application_id"`
	RawText           string             `json:"raw_text"`
	ExtractedKeywords []string           `json:"extracted_keywords"`
	AiSummary         *string            `json:"ai_summary"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateJobDescriptionSQL(ctx context.Context, arg CreateJobDescriptionSQLParams) (CreateJobDescriptionSQLRow, error) {
	row := q.db.QueryRow(ctx, createJobDescriptionSQL,
		arg.ApplicationID,
		arg.RawText,
		arg.ExtractedKeywords,
		arg.AiSummary,
	)
	var i CreateJobDescriptionSQLRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.RawText,
		&i.ExtractedKeywords,
		&i.AiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobDescriptionByApplicationSQL = `-- name: GetJobDescriptionByApplicationSQL :one
SELECT id::text, application_id::text, raw_text, extracted_keywords, ai_summary, created_at, updated_at
FROM job_descriptions
WHERE application_id = $1::uuid
ORDER BY created_at DESC
LIMIT 1
`

type GetJobDescriptionByApplicationSQLRow struct {
	ID                string             `json:"id"`
	ApplicationID     string             `json:"application_id"`
	RawText           string             `json:"raw_text"`
	ExtractedKeywords []string           `json:"extracted_keywords"`
	AiSummary         *string            `json:"ai_summary"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetJobDescriptionByApplicationSQL(ctx context.Context, applicationID string) (GetJobDescriptionByApplicationSQLRow, error) {
	row := q.db.QueryRow(ctx, getJobDescriptionByApplicationSQL, applicationID)
	var i GetJobDescriptionByApplicationSQLRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.RawText,
		&i.ExtractedKeywords,
		&i.AiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobDescriptionSQL = `-- name: UpdateJobDescriptionSQL :one
UPDATE job_descriptions
SET
    raw_text = COALESCE($1, raw_text),
    extracted_keywords = CASE WHEN $2::boolean THEN $3 ELSE extracted_keywords END,
    ai_summary = COALESCE($4, ai_summary),
    updated_at = now()
WHERE id = $5::uuid
RETURNING id::text, application_id::text, raw_text, extracted_keywords, ai_summary, created_at, updated_at
`

type UpdateJobDescriptionSQLParams struct {
	RawText           *string  `json:"raw_text"`
	SetKeywords       bool     `json:"set_keywords"`
	ExtractedKeywords []string `json:"extracted_keywords"`
	AiSummary         *string  `json:"ai_summary"`
	ID                string   `json:"id"`
}

type UpdateJobDescriptionSQLRow struct {
	ID                string             `json:"id"`
	ApplicationID     string             `json:"application_id"`
	RawText           string             `json:"raw_text"`
	ExtractedKeywords []string           `json:"extracted_keywords"`
	AiSummary         *string            `json:"ai_summary"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateJobDescriptionSQL(ctx context.Context, arg UpdateJobDescriptionSQLParams) (UpdateJobDescriptionSQLRow, error) {
	row := q.db.QueryRow(ctx, updateJobDescriptionSQL,
		arg.RawText,
		arg.SetKeywords,
		arg.ExtractedKeywords,
		arg.AiSummary,
		arg.ID,
	)
	var i UpdateJobDescriptionSQLRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.RawText,
		&i.ExtractedKeywords,
		&i.AiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
