// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: applications.sql

package queries

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplicationSQL = `-- name: CreateApplicationSQL :one
INSERT INTO applications (
    company_id,
    resume_version_id,
    title,
    role_track,
    source,
    status,
    location,
    employment_type,
    job_url,
    portal_account,
    portal_password,
    applied_at,
    deadline_at,
    notes
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5,
    COALESCE($6, 'saved'),
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id::text, company_id::text, COALESCE(resume_version_id::text, '') AS resume_version_id, title, role_track, source,
    status, location, employment_type, job_url, portal_account, portal_password, applied_at, deadline_at, notes, created_at, updated_at
`

type CreateApplicationSQLParams struct {
	CompanyID       string      `json:"company_id"`
	ResumeVersionID *string     `json:"resume_version_id"`
	Title           string      `json:"title"`
	RoleTrack       string      `json:"role_track"`
	Source          *string     `json:"source"`
	Status          interface{} `json:"status"`
	Location        *string     `json:"location"`
	EmploymentType  *string     `json:"employment_type"`
	JobUrl          *string     `json:"job_url"`
	PortalAccount   *string     `json:"portal_account"`
	PortalPassword  *string     `json:"portal_password"`
	AppliedAt       *time.Time  `json:"applied_at"`
	DeadlineAt      *time.Time  `json:"deadline_at"`
	Notes           *string     `json:"notes"`
}

type CreateApplicationSQLRow struct {
	ID              string             `json:"id"`
	CompanyID       string             `json:"company_id"`
	ResumeVersionID interface{}        `json:"resume_version_id"`
	Title           string             `json:"title"`
	RoleTrack       string             `json:"role_track"`
	Source          *string            `json:"source"`
	Status          string             `json:"status"`
	Location        *string            `json:"location"`
	EmploymentType  *string            `json:"employment_type"`
	JobUrl          *string            `json:"job_url"`
	PortalAccount   *string            `json:"portal_account"`
	PortalPassword  *string            `json:"portal_password"`
	AppliedAt       *time.Time         `json:"applied_at"`
	DeadlineAt      *time.Time         `json:"deadline_at"`
	Notes           *string            `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateApplicationSQL(ctx context.Context, arg CreateApplicationSQLParams) (CreateApplicationSQLRow, error) {
	row := q.db.QueryRow(ctx, createApplicationSQL,
		arg.CompanyID,
		arg.ResumeVersionID,
		arg.Title,
		arg.RoleTrack,
		arg.Source,
		arg.Status,
		arg.Location,
		arg.EmploymentType,
		arg.JobUrl,
		arg.PortalAccount,
		arg.PortalPassword,
		arg.AppliedAt,
		arg.DeadlineAt,
		arg.Notes,
	)
	var i CreateApplicationSQLRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ResumeVersionID,
		&i.Title,
		&i.RoleTrack,
		&i.Source,
		&i.Status,
		&i.Location,
		&i.EmploymentType,
		&i.JobUrl,
		&i.PortalAccount,
		&i.PortalPassword,
		&i.AppliedAt,
		&i.DeadlineAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplicationRowCount = `-- name: DeleteApplicationRowCount :execrows
DELETE FROM applications
WHERE id = $1::uuid
`

func (q *Queries) DeleteApplicationRowCount(ctx context.Context, dollar_1 string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplicationRowCount, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplicationSQL = `-- name: GetApplicationSQL :one
SELECT id::text, company_id::text, COALESCE(resume_version_id::text, '') AS resume_version_id, title, role_track, source,
    status, location, employment_type, job_url, portal_account, portal_password, applied_at, deadline_at, notes, created_at, updated_at
FROM applications
WHERE id = $1::uuid
`

type GetApplicationSQLRow struct {
	ID              string             `json:"id"`
	CompanyID       string             `json:"company_id"`
	ResumeVersionID interface{}        `json:"resume_version_id"`
	Title           string             `json:"title"`
	RoleTrack       string             `json:"role_track"`
	Source          *string            `json:"source"`
	Status          string             `json:"status"`
	Location        *string            `json:"location"`
	EmploymentType  *string            `json:"employment_type"`
	JobUrl          *string            `json:"job_url"`
	PortalAccount   *string            `json:"portal_account"`
	PortalPassword  *string            `json:"portal_password"`
	AppliedAt       *time.Time         `json:"applied_at"`
	DeadlineAt      *time.Time         `json:"deadline_at"`
	Notes           *string            `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetApplicationSQL(ctx context.Context, id string) (GetApplicationSQLRow, error) {
	row := q.db.QueryRow(ctx, getApplicationSQL, id)
	var i GetApplicationSQLRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ResumeVersionID,
		&i.Title,
		&i.RoleTrack,
		&i.Source,
		&i.Status,
		&i.Location,
		&i.EmploymentType,
		&i.JobUrl,
		&i.PortalAccount,
		&i.PortalPassword,
		&i.AppliedAt,
		&i.DeadlineAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationsSQL = `-- name: ListApplicationsSQL :many
SELECT id::text, company_id::text, COALESCE(resume_version_id::text, '') AS resume_version_id, title, role_track, source,
    status, location, employment_type, job_url, portal_account, portal_password, applied_at, deadline_at, notes, created_at, updated_at
FROM applications
ORDER BY created_at DESC
LIMIT 200
`

type ListApplicationsSQLRow struct {
	ID              string             `json:"id"`
	CompanyID       string             `json:"company_id"`
	ResumeVersionID interface{}        `json:"resume_version_id"`
	Title           string             `json:"title"`
	RoleTrack       string             `json:"role_track"`
	Source          *string            `json:"source"`
	Status          string             `json:"status"`
	Location        *string            `json:"location"`
	EmploymentType  *string            `json:"employment_type"`
	JobUrl          *string            `json:"job_url"`
	PortalAccount   *string            `json:"portal_account"`
	PortalPassword  *string            `json:"portal_password"`
	AppliedAt       *time.Time         `json:"applied_at"`
	DeadlineAt      *time.Time         `json:"deadline_at"`
	Notes           *string            `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListApplicationsSQL(ctx context.Context) ([]ListApplicationsSQLRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsSQLRow{}
	for rows.Next() {
		var i ListApplicationsSQLRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ResumeVersionID,
			&i.Title,
			&i.RoleTrack,
			&i.Source,
			&i.Status,
			&i.Location,
			&i.EmploymentType,
			&i.JobUrl,
			&i.PortalAccount,
			&i.PortalPassword,
			&i.AppliedAt,
			&i.DeadlineAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationSQL = `-- name: UpdateApplicationSQL :one
UPDATE applications
SET
    company_id = COALESCE($1::uuid, company_id),
    resume_version_id = COALESCE($2::uuid, resume_version_id),
    title = COALESCE($3, title),
    role_track = COALESCE($4, role_track),
    status = COALESCE($5, status),
    source = COALESCE($6, source),
    location = COALESCE($7, location),
    employment_type = COALESCE($8, employment_type),
    job_url = COALESCE($9, job_url),
    portal_account = COALESCE($10, portal_account),
    portal_password = COALESCE($11, portal_password),
    applied_at = COALESCE($12, applied_at),
    deadline_at = COALESCE($13, deadline_at),
    notes = COALESCE($14, notes),
    updated_at = now()
WHERE id = $15::uuid
RETURNING id::text, company_id::text, COALESCE(resume_version_id::text, '') AS resume_version_id, title, role_track, source,
    status, location, employment_type, job_url, portal_account, portal_password, applied_at, deadline_at, notes, created_at, updated_at
`

type UpdateApplicationSQLParams struct {
	CompanyID       *string    `json:"company_id"`
	ResumeVersionID *string    `json:"resume_version_id"`
	Title           *string    `json:"title"`
	RoleTrack       *string    `json:"role_track"`
	Status          *string    `json:"status"`
	Source          *string    `json:"source"`
	Location        *string    `json:"location"`
	EmploymentType  *string    `json:"employment_type"`
	JobUrl          *string    `json:"job_url"`
	PortalAccount   *string    `json:"portal_account"`
	PortalPassword  *string    `json:"portal_password"`
	AppliedAt       *time.Time `json:"applied_at"`
	DeadlineAt      *time.Time `json:"deadline_at"`
	Notes           *string    `json:"notes"`
	ID              string     `json:"id"`
}

type UpdateApplicationSQLRow struct {
	ID              string             `json:"id"`
	CompanyID       string             `json:"company_id"`
	ResumeVersionID interface{}        `json:"resume_version_id"`
	Title           string             `json:"title"`
	RoleTrack       string             `json:"role_track"`
	Source          *string            `json:"source"`
	Status          string             `json:"status"`
	Location        *string            `json:"location"`
	EmploymentType  *string            `json:"employment_type"`
	JobUrl          *string            `json:"job_url"`
	PortalAccount   *string            `json:"portal_account"`
	PortalPassword  *string            `json:"portal_password"`
	AppliedAt       *time.Time         `json:"applied_at"`
	DeadlineAt      *time.Time         `json:"deadline_at"`
	Notes           *string            `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateApplicationSQL(ctx context.Context, arg UpdateApplicationSQLParams) (UpdateApplicationSQLRow, error) {
	row := q.db.QueryRow(ctx, updateApplicationSQL,
		arg.CompanyID,
		arg.ResumeVersionID,
		arg.Title,
		arg.RoleTrack,
		arg.Status,
		arg.Source,
		arg.Location,
		arg.EmploymentType,
		arg.JobUrl,
		arg.PortalAccount,
		arg.PortalPassword,
		arg.AppliedAt,
		arg.DeadlineAt,
		arg.Notes,
		arg.ID,
	)
	var i UpdateApplicationSQLRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ResumeVersionID,
		&i.Title,
		&i.RoleTrack,
		&i.Source,
		&i.Status,
		&i.Location,
		&i.EmploymentType,
		&i.JobUrl,
		&i.PortalAccount,
		&i.PortalPassword,
		&i.AppliedAt,
		&i.DeadlineAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationStatusSQL = `-- name: UpdateApplicationStatusSQL :one
UPDATE applications
SET status = $1, updated_at = now()
WHERE id = $2::uuid
RETURNING id::text, company_id::text, COALESCE(resume_version_id::text, '') AS resume_version_id, title, role_track, source,
    status, location, employment_type, job_url, portal_account, portal_password, applied_at, deadline_at, notes, created_at, updated_at
`

type UpdateApplicationStatusSQLParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

type UpdateApplicationStatusSQLRow struct {
	ID              string             `json:"id"`
	CompanyID       string             `json:"company_id"`
	ResumeVersionID interface{}        `json:"resume_version_id"`
	Title           string             `json:"title"`
	RoleTrack       string             `json:"role_track"`
	Source          *string            `json:"source"`
	Status          string             `json:"status"`
	Location        *string            `json:"location"`
	EmploymentType  *string            `json:"employment_type"`
	JobUrl          *string            `json:"job_url"`
	PortalAccount   *string            `json:"portal_account"`
	PortalPassword  *string            `json:"portal_password"`
	AppliedAt       *time.Time         `json:"applied_at"`
	DeadlineAt      *time.Time         `json:"deadline_at"`
	Notes           *string            `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateApplicationStatusSQL(ctx context.Context, arg UpdateApplicationStatusSQLParams) (UpdateApplicationStatusSQLRow, error) {
	row := q.db.QueryRow(ctx, updateApplicationStatusSQL, arg.Status, arg.ID)
	var i UpdateApplicationStatusSQLRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ResumeVersionID,
		&i.Title,
		&i.RoleTrack,
		&i.Source,
		&i.Status,
		&i.Location,
		&i.EmploymentType,
		&i.JobUrl,
		&i.PortalAccount,
		&i.PortalPassword,
		&i.AppliedAt,
		&i.DeadlineAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
