// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_logs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLogSQL = `-- name: CreateAuditLogSQL :one
INSERT INTO audit_logs (entity_type, entity_id, action, old_value, new_value)
VALUES (
    $1,
    $2::uuid,
    $3,
    $4::jsonb,
    $5::jsonb
)
RETURNING id::text, entity_type, entity_id::text, action, old_value, new_value, created_at
`

type CreateAuditLogSQLParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Action     string `json:"action"`
	OldValue   []byte `json:"old_value"`
	NewValue   []byte `json:"new_value"`
}

type CreateAuditLogSQLRow struct {
	ID         string             `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   string             `json:"entity_id"`
	Action     string             `json:"action"`
	OldValue   []byte             `json:"old_value"`
	NewValue   []byte             `json:"new_value"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuditLogSQL(ctx context.Context, arg CreateAuditLogSQLParams) (CreateAuditLogSQLRow, error) {
	row := q.db.QueryRow(ctx, createAuditLogSQL,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.OldValue,
		arg.NewValue,
	)
	var i CreateAuditLogSQLRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.OldValue,
		&i.NewValue,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsForEntitySQL = `-- name: ListAuditLogsForEntitySQL :many
SELECT id::text, entity_type, entity_id::text, action, old_value, new_value, created_at
FROM audit_logs
WHERE entity_type = $1 AND entity_id = $2::uuid
ORDER BY created_at DESC
`

type ListAuditLogsForEntitySQLParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

type ListAuditLogsForEntitySQLRow struct {
	ID         string             `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   string             `json:"entity_id"`
	Action     string             `json:"action"`
	OldValue   []byte             `json:"old_value"`
	NewValue   []byte             `json:"new_value"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAuditLogsForEntitySQL(ctx context.Context, arg ListAuditLogsForEntitySQLParams) ([]ListAuditLogsForEntitySQLRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForEntitySQL, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsForEntitySQLRow{}
	for rows.Next() {
		var i ListAuditLogsForEntitySQLRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
