// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: companies.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompanySQL = `-- name: CreateCompanySQL :one
INSERT INTO companies (name, website, industry, location, notes)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id::text, name, website, industry, location, notes, created_at, updated_at
`

type CreateCompanySQLParams struct {
	Name     string  `json:"name"`
	Website  *string `json:"website"`
	Industry *string `json:"industry"`
	Location *string `json:"location"`
	Notes    *string `json:"notes"`
}

type CreateCompanySQLRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Website   *string            `json:"website"`
	Industry  *string            `json:"industry"`
	Location  *string            `json:"location"`
	Notes     *string            `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCompanySQL(ctx context.Context, arg CreateCompanySQLParams) (CreateCompanySQLRow, error) {
	row := q.db.QueryRow(ctx, createCompanySQL,
		arg.Name,
		arg.Website,
		arg.Industry,
		arg.Location,
		arg.Notes,
	)
	var i CreateCompanySQLRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.Industry,
		&i.Location,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompanyRowCount = `-- name: DeleteCompanyRowCount :execrows
DELETE FROM companies
WHERE id = $1::uuid
`

func (q *Queries) DeleteCompanyRowCount(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompanyRowCount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompanySQL = `-- name: GetCompanySQL :one
SELECT id::text, name, website, industry, location, notes, created_at, updated_at
FROM companies
WHERE id = $1::uuid
`

type GetCompanySQLRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Website   *string            `json:"website"`
	Industry  *string            `json:"industry"`
	Location  *string            `json:"location"`
	Notes     *string            `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCompanySQL(ctx context.Context, id string) (GetCompanySQLRow, error) {
	row := q.db.QueryRow(ctx, getCompanySQL, id)
	var i GetCompanySQLRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.Industry,
		&i.Location,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompaniesSQL = `-- name: ListCompaniesSQL :many
SELECT id::text, name, website, industry, location, notes, created_at, updated_at
FROM companies
ORDER BY created_at DESC
LIMIT 200
`

type ListCompaniesSQLRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Website   *string            `json:"website"`
	Industry  *string            `json:"industry"`
	Location  *string            `json:"location"`
	Notes     *string            `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCompaniesSQL(ctx context.Context) ([]ListCompaniesSQLRow, error) {
	rows, err := q.db.Query(ctx, listCompaniesSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesSQLRow{}
	for rows.Next() {
		var i ListCompaniesSQLRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Website,
			&i.Industry,
			&i.Location,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanySQL = `-- name: UpdateCompanySQL :one
UPDATE companies
SET
    name = COALESCE($1, name),
    website = COALESCE($2, website),
    industry = COALESCE($3, industry),
    location = COALESCE($4, location),
    notes = COALESCE($5, notes),
    updated_at = now()
WHERE id = $6::uuid
RETURNING id::text, name, website, industry, location, notes, created_at, updated_at
`

type UpdateCompanySQLParams struct {
	Name     *string `json:"name"`
	Website  *string `json:"website"`
	Industry *string `json:"industry"`
	Location *string `json:"location"`
	Notes    *string `json:"notes"`
	ID       string  `json:"id"`
}

type UpdateCompanySQLRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Website   *string            `json:"website"`
	Industry  *string            `json:"industry"`
	Location  *string            `json:"location"`
	Notes     *string            `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCompanySQL(ctx context.Context, arg UpdateCompanySQLParams) (UpdateCompanySQLRow, error) {
	row := q.db.QueryRow(ctx, updateCompanySQL,
		arg.Name,
		arg.Website,
		arg.Industry,
		arg.Location,
		arg.Notes,
		arg.ID,
	)
	var i UpdateCompanySQLRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.Industry,
		&i.Location,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
