// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contacts.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContactSQL = `-- name: CreateContactSQL :one
INSERT INTO contacts (company_id, name, role, email, linkedin_url, relationship, notes)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id::text, company_id::text, name, role, email, linkedin_url, relationship, notes, created_at, updated_at
`

type CreateContactSQLParams struct {
	CompanyID    string  `json:"company_id"`
	Name         string  `json:"name"`
	Role         *string `json:"role"`
	Email        *string `json:"email"`
	LinkedinUrl  *string `json:"linkedin_url"`
	Relationship *string `json:"relationship"`
	Notes        *string `json:"notes"`
}

type CreateContactSQLRow struct {
	ID           string             `json:"id"`
	CompanyID    string             `json:"company_id"`
	Name         string             `json:"name"`
	Role         *string            `json:"role"`
	Email        *string            `json:"email"`
	LinkedinUrl  *string            `json:"linkedin_url"`
	Relationship *string            `json:"relationship"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateContactSQL(ctx context.Context, arg CreateContactSQLParams) (CreateContactSQLRow, error) {
	row := q.db.QueryRow(ctx, createContactSQL,
		arg.CompanyID,
		arg.Name,
		arg.Role,
		arg.Email,
		arg.LinkedinUrl,
		arg.Relationship,
		arg.Notes,
	)
	var i CreateContactSQLRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.LinkedinUrl,
		&i.Relationship,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContactRowCount = `-- name: DeleteContactRowCount :execrows
DELETE FROM contacts
WHERE id = $1::uuid
`

func (q *Queries) DeleteContactRowCount(ctx context.Context, dollar_1 string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContactRowCount, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContactSQL = `-- name: GetContactSQL :one
SELECT id::text, company_id::text, name, role, email, linkedin_url, relationship, notes, created_at, updated_at
FROM contacts
WHERE id = $1::uuid
`

type GetContactSQLRow struct {
	ID           string             `json:"id"`
	CompanyID    string             `json:"company_id"`
	Name         string             `json:"name"`
	Role         *string            `json:"role"`
	Email        *string            `json:"email"`
	LinkedinUrl  *string            `json:"linkedin_url"`
	Relationship *string            `json:"relationship"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetContactSQL(ctx context.Context, id string) (GetContactSQLRow, error) {
	row := q.db.QueryRow(ctx, getContactSQL, id)
	var i GetContactSQLRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.LinkedinUrl,
		&i.Relationship,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContactsSQL = `-- name: ListContactsSQL :many
SELECT id::text, company_id::text, name, role, email, linkedin_url, relationship, notes, created_at, updated_at
FROM contacts
ORDER BY created_at DESC
LIMIT 200
`

type ListContactsSQLRow struct {
	ID           string             `json:"id"`
	CompanyID    string             `json:"company_id"`
	Name         string             `json:"name"`
	Role         *string            `json:"role"`
	Email        *string            `json:"email"`
	LinkedinUrl  *string            `json:"linkedin_url"`
	Relationship *string            `json:"relationship"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListContactsSQL(ctx context.Context) ([]ListContactsSQLRow, error) {
	rows, err := q.db.Query(ctx, listContactsSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsSQLRow{}
	for rows.Next() {
		var i ListContactsSQLRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Role,
			&i.Email,
			&i.LinkedinUrl,
			&i.Relationship,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactSQL = `-- name: UpdateContactSQL :one
UPDATE contacts
SET
    company_id = COALESCE($1::uuid, company_id),
    name = COALESCE($2, name),
    role = COALESCE($3, role),
    email = COALESCE($4, email),
    linkedin_url = COALESCE($5, linkedin_url),
    relationship = COALESCE($6, relationship),
    notes = COALESCE($7, notes),
    updated_at = now()
WHERE id = $8::uuid
RETURNING id::text, company_id::text, name, role, email, linkedin_url, relationship, notes, created_at, updated_at
`

type UpdateContactSQLParams struct {
	CompanyID    *string `json:"company_id"`
	Name         *string `json:"name"`
	Role         *string `json:"role"`
	Email        *string `json:"email"`
	LinkedinUrl  *string `json:"linkedin_url"`
	Relationship *string `json:"relationship"`
	Notes        *string `json:"notes"`
	ID           string  `json:"id"`
}

type UpdateContactSQLRow struct {
	ID           string             `json:"id"`
	CompanyID    string             `json:"company_id"`
	Name         string             `json:"name"`
	Role         *string            `json:"role"`
	Email        *string            `json:"email"`
	LinkedinUrl  *string            `json:"linkedin_url"`
	Relationship *string            `json:"relationship"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateContactSQL(ctx context.Context, arg UpdateContactSQLParams) (UpdateContactSQLRow, error) {
	row := q.db.QueryRow(ctx, updateContactSQL,
		arg.CompanyID,
		arg.Name,
		arg.Role,
		arg.Email,
		arg.LinkedinUrl,
		arg.Relationship,
		arg.Notes,
		arg.ID,
	)
	var i UpdateContactSQLRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.LinkedinUrl,
		&i.Relationship,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
