// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: interviews.sql

package queries

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInterviewRoundSQL = `-- name: CreateInterviewRoundSQL :one
INSERT INTO interview_rounds (application_id, round_type, scheduled_at, interviewer, notes, outcome)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id::text, application_id::text, round_type, scheduled_at, interviewer, notes, outcome, created_at, updated_at
`

type CreateInterviewRoundSQLParams struct {
	ApplicationID string     `json:"application_id"`
	RoundType     string     `json:"round_type"`
	ScheduledAt   *time.Time `json:"scheduled_at"`
	Interviewer   *string    `json:"interviewer"`
	Notes         *string    `json:"notes"`
	Outcome       *string    `json:"outcome"`
}

type CreateInterviewRoundSQLRow struct {
	ID            string             `json:"id"`
	ApplicationID string             `json:"application_id"`
	RoundType     string             `json:"round_type"`
	ScheduledAt   *time.Time         `json:"scheduled_at"`
	Interviewer   *string            `json:"interviewer"`
	Notes         *string            `json:"notes"`
	Outcome       *string            `json:"outcome"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateInterviewRoundSQL(ctx context.Context, arg CreateInterviewRoundSQLParams) (CreateInterviewRoundSQLRow, error) {
	row := q.db.QueryRow(ctx, createInterviewRoundSQL,
		arg.ApplicationID,
		arg.RoundType,
		arg.ScheduledAt,
		arg.Interviewer,
		arg.Notes,
		arg.Outcome,
	)
	var i CreateInterviewRoundSQLRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.RoundType,
		&i.ScheduledAt,
		&i.Interviewer,
		&i.Notes,
		&i.Outcome,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInterviewRoundRowCount = `-- name: DeleteInterviewRoundRowCount :execrows
DELETE FROM interview_rounds
WHERE id = $1::uuid
`

func (q *Queries) DeleteInterviewRoundRowCount(ctx context.Context, dollar_1 string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInterviewRoundRowCount, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listInterviewRoundsByApplicationSQL = `-- name: ListInterviewRoundsByApplicationSQL :many
SELECT id::text, application_id::text, round_type, scheduled_at, interviewer, notes, outcome, created_at, updated_at
FROM interview_rounds
WHERE application_id = $1::uuid
ORDER BY scheduled_at NULLS LAST, created_at DESC
`

type ListInterviewRoundsByApplicationSQLRow struct {
	ID            string             `json:"id"`
	ApplicationID string             `json:"application_id"`
	RoundType     string             `json:"round_type"`
	ScheduledAt   *time.Time         `json:"scheduled_at"`
	Interviewer   *string            `json:"interviewer"`
	Notes         *string            `json:"notes"`
	Outcome       *string            `json:"outcome"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListInterviewRoundsByApplicationSQL(ctx context.Context, applicationID string) ([]ListInterviewRoundsByApplicationSQLRow, error) {
	rows, err := q.db.Query(ctx, listInterviewRoundsByApplicationSQL, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInterviewRoundsByApplicationSQLRow{}
	for rows.Next() {
		var i ListInterviewRoundsByApplicationSQLRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.RoundType,
			&i.ScheduledAt,
			&i.Interviewer,
			&i.Notes,
			&i.Outcome,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewRoundSQL = `-- name: UpdateInterviewRoundSQL :one
UPDATE interview_rounds
SET
    round_type = COALESCE($1, round_type),
    scheduled_at = COALESCE($2, scheduled_at),
    interviewer = COALESCE($3, interviewer),
    notes = COALESCE($4, notes),
    outcome = COALESCE($5, outcome),
    updated_at = now()
WHERE id = $6::uuid
RETURNING id::text, application_id::text, round_type, scheduled_at, interviewer, notes, outcome, created_at, updated_at
`

type UpdateInterviewRoundSQLParams struct {
	RoundType   *string    `json:"round_type"`
	ScheduledAt *time.Time `json:"scheduled_at"`
	Interviewer *string    `json:"interviewer"`
	Notes       *string    `json:"notes"`
	Outcome     *string    `json:"outcome"`
	ID          string     `json:"id"`
}

type UpdateInterviewRoundSQLRow struct {
	ID            string             `json:"id"`
	ApplicationID string             `json:"application_id"`
	RoundType     string             `json:"round_type"`
	ScheduledAt   *time.Time         `json:"scheduled_at"`
	Interviewer   *string            `json:"interviewer"`
	Notes         *string            `json:"notes"`
	Outcome       *string            `json:"outcome"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateInterviewRoundSQL(ctx context.Context, arg UpdateInterviewRoundSQLParams) (UpdateInterviewRoundSQLRow, error) {
	row := q.db.QueryRow(ctx, updateInterviewRoundSQL,
		arg.RoundType,
		arg.ScheduledAt,
		arg.Interviewer,
		arg.Notes,
		arg.Outcome,
		arg.ID,
	)
	var i UpdateInterviewRoundSQLRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.RoundType,
		&i.ScheduledAt,
		&i.Interviewer,
		&i.Notes,
		&i.Outcome,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
