// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reminders.sql

package queries

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFailedReminderJobSQL = `-- name: CreateFailedReminderJobSQL :one
INSERT INTO failed_reminder_jobs (reminder_id, error_message, retry_count, payload)
VALUES ($1::uuid, $2, $3, $4::jsonb)
RETURNING id::text, COALESCE(reminder_id::text, '') AS reminder_id, error_message, retry_count, payload, failed_at
`

type CreateFailedReminderJobSQLParams struct {
	ReminderID   *string `json:"reminder_id"`
	ErrorMessage string  `json:"error_message"`
	RetryCount   int32   `json:"retry_count"`
	Payload      []byte  `json:"payload"`
}

type CreateFailedReminderJobSQLRow struct {
	ID           string             `json:"id"`
	ReminderID   interface{}        `json:"reminder_id"`
	ErrorMessage string             `json:"error_message"`
	RetryCount   int32              `json:"retry_count"`
	Payload      []byte             `json:"payload"`
	FailedAt     pgtype.Timestamptz `json:"failed_at"`
}

func (q *Queries) CreateFailedReminderJobSQL(ctx context.Context, arg CreateFailedReminderJobSQLParams) (CreateFailedReminderJobSQLRow, error) {
	row := q.db.QueryRow(ctx, createFailedReminderJobSQL,
		arg.ReminderID,
		arg.ErrorMessage,
		arg.RetryCount,
		arg.Payload,
	)
	var i CreateFailedReminderJobSQLRow
	err := row.Scan(
		&i.ID,
		&i.ReminderID,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.Payload,
		&i.FailedAt,
	)
	return i, err
}

const createReminderDeliverySQL = `-- name: CreateReminderDeliverySQL :one
INSERT INTO reminder_deliveries (reminder_id, idempotency_key)
VALUES ($1::uuid, $2)
ON CONFLICT (idempotency_key) DO UPDATE SET idempotency_key = EXCLUDED.idempotency_key
RETURNING id::text, reminder_id::text, idempotency_key, delivered_at, created_at
`

type CreateReminderDeliverySQLParams struct {
	ReminderID     string `json:"reminder_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

type CreateReminderDeliverySQLRow struct {
	ID             string             `json:"id"`
	ReminderID     string             `json:"reminder_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateReminderDeliverySQL(ctx context.Context, arg CreateReminderDeliverySQLParams) (CreateReminderDeliverySQLRow, error) {
	row := q.db.QueryRow(ctx, createReminderDeliverySQL, arg.ReminderID, arg.IdempotencyKey)
	var i CreateReminderDeliverySQLRow
	err := row.Scan(
		&i.ID,
		&i.ReminderID,
		&i.IdempotencyKey,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createReminderSQL = `-- name: CreateReminderSQL :one
INSERT INTO reminders (application_id, contact_id, title, description, due_at, idempotency_key)
VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5,
    $6
)
RETURNING id::text, application_id::text, COALESCE(contact_id::text, '') AS contact_id, title, description, due_at, status,
    idempotency_key, retry_count, last_error, delivered_at, created_at, updated_at
`

type CreateReminderSQLParams struct {
	ApplicationID  string             `json:"application_id"`
	ContactID      *string            `json:"contact_id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	IdempotencyKey string             `json:"idempotency_key"`
}

type CreateReminderSQLRow struct {
	ID             string             `json:"id"`
	ApplicationID  string             `json:"application_id"`
	ContactID      interface{}        `json:"contact_id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	RetryCount     int32              `json:"retry_count"`
	LastError      *string            `json:"last_error"`
	DeliveredAt    *time.Time         `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateReminderSQL(ctx context.Context, arg CreateReminderSQLParams) (CreateReminderSQLRow, error) {
	row := q.db.QueryRow(ctx, createReminderSQL,
		arg.ApplicationID,
		arg.ContactID,
		arg.Title,
		arg.Description,
		arg.DueAt,
		arg.IdempotencyKey,
	)
	var i CreateReminderSQLRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ContactID,
		&i.Title,
		&i.Description,
		&i.DueAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.RetryCount,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReminderRowCount = `-- name: DeleteReminderRowCount :execrows
DELETE FROM reminders
WHERE id = $1::uuid
`

func (q *Queries) DeleteReminderRowCount(ctx context.Context, dollar_1 string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReminderRowCount, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReminderSQL = `-- name: GetReminderSQL :one
SELECT id::text, application_id::text, COALESCE(contact_id::text, '') AS contact_id, title, description, due_at, status,
    idempotency_key, retry_count, last_error, delivered_at, created_at, updated_at
FROM reminders
WHERE id = $1::uuid
`

type GetReminderSQLRow struct {
	ID             string             `json:"id"`
	ApplicationID  string             `json:"application_id"`
	ContactID      interface{}        `json:"contact_id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	RetryCount     int32              `json:"retry_count"`
	LastError      *string            `json:"last_error"`
	DeliveredAt    *time.Time         `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetReminderSQL(ctx context.Context, id string) (GetReminderSQLRow, error) {
	row := q.db.QueryRow(ctx, getReminderSQL, id)
	var i GetReminderSQLRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ContactID,
		&i.Title,
		&i.Description,
		&i.DueAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.RetryCount,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueRemindersSQL = `-- name: ListDueRemindersSQL :many
SELECT id::text, application_id::text, COALESCE(contact_id::text, '') AS contact_id, title, description, due_at, status,
    idempotency_key, retry_count, last_error, delivered_at, created_at, updated_at
FROM reminders
WHERE status = 'pending' AND due_at <= $1
ORDER BY due_at ASC
`

type ListDueRemindersSQLRow struct {
	ID             string             `json:"id"`
	ApplicationID  string             `json:"application_id"`
	ContactID      interface{}        `json:"contact_id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	RetryCount     int32              `json:"retry_count"`
	LastError      *string            `json:"last_error"`
	DeliveredAt    *time.Time         `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDueRemindersSQL(ctx context.Context, now pgtype.Timestamptz) ([]ListDueRemindersSQLRow, error) {
	rows, err := q.db.Query(ctx, listDueRemindersSQL, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueRemindersSQLRow{}
	for rows.Next() {
		var i ListDueRemindersSQLRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ContactID,
			&i.Title,
			&i.Description,
			&i.DueAt,
			&i.Status,
			&i.IdempotencyKey,
			&i.RetryCount,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemindersSQL = `-- name: ListRemindersSQL :many
SELECT id::text, application_id::text, COALESCE(contact_id::text, '') AS contact_id, title, description, due_at, status,
    idempotency_key, retry_count, last_error, delivered_at, created_at, updated_at
FROM reminders
ORDER BY due_at ASC, created_at DESC
LIMIT 200
`

type ListRemindersSQLRow struct {
	ID             string             `json:"id"`
	ApplicationID  string             `json:"application_id"`
	ContactID      interface{}        `json:"contact_id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	RetryCount     int32              `json:"retry_count"`
	LastError      *string            `json:"last_error"`
	DeliveredAt    *time.Time         `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRemindersSQL(ctx context.Context) ([]ListRemindersSQLRow, error) {
	rows, err := q.db.Query(ctx, listRemindersSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRemindersSQLRow{}
	for rows.Next() {
		var i ListRemindersSQLRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ContactID,
			&i.Title,
			&i.Description,
			&i.DueAt,
			&i.Status,
			&i.IdempotencyKey,
			&i.RetryCount,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderRetrySQL = `-- name: MarkReminderRetrySQL :one
UPDATE reminders
SET status = $1, retry_count = $2, last_error = $3, updated_at = now()
WHERE id = $4::uuid
RETURNING id::text, application_id::text, COALESCE(contact_id::text, '') AS contact_id, title, description, due_at, status,
    idempotency_key, retry_count, last_error, delivered_at, created_at, updated_at
`

type MarkReminderRetrySQLParams struct {
	Status     string  `json:"status"`
	RetryCount int32   `json:"retry_count"`
	LastError  *string `json:"last_error"`
	ID         string  `json:"id"`
}

type MarkReminderRetrySQLRow struct {
	ID             string             `json:"id"`
	ApplicationID  string             `json:"application_id"`
	ContactID      interface{}        `json:"contact_id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	RetryCount     int32              `json:"retry_count"`
	LastError      *string            `json:"last_error"`
	DeliveredAt    *time.Time         `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkReminderRetrySQL(ctx context.Context, arg MarkReminderRetrySQLParams) (MarkReminderRetrySQLRow, error) {
	row := q.db.QueryRow(ctx, markReminderRetrySQL,
		arg.Status,
		arg.RetryCount,
		arg.LastError,
		arg.ID,
	)
	var i MarkReminderRetrySQLRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ContactID,
		&i.Title,
		&i.Description,
		&i.DueAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.RetryCount,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markReminderSentSQL = `-- name: MarkReminderSentSQL :one
UPDATE reminders
SET status = 'sent', delivered_at = now(), last_error = NULL, updated_at = now()
WHERE id = $1::uuid
RETURNING id::text, application_id::text, COALESCE(contact_id::text, '') AS contact_id, title, description, due_at, status,
    idempotency_key, retry_count, last_error, delivered_at, created_at, updated_at
`

type MarkReminderSentSQLRow struct {
	ID             string             `json:"id"`
	ApplicationID  string             `json:"application_id"`
	ContactID      interface{}        `json:"contact_id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	RetryCount     int32              `json:"retry_count"`
	LastError      *string            `json:"last_error"`
	DeliveredAt    *time.Time         `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkReminderSentSQL(ctx context.Context, id string) (MarkReminderSentSQLRow, error) {
	row := q.db.QueryRow(ctx, markReminderSentSQL, id)
	var i MarkReminderSentSQLRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ContactID,
		&i.Title,
		&i.Description,
		&i.DueAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.RetryCount,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReminderSQL = `-- name: UpdateReminderSQL :one
UPDATE reminders
SET
    application_id = COALESCE($1::uuid, application_id),
    contact_id = COALESCE($2::uuid, contact_id),
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    due_at = COALESCE($5, due_at),
    updated_at = now()
WHERE id = $6::uuid
RETURNING id::text, application_id::text, COALESCE(contact_id::text, '') AS contact_id, title, description, due_at, status,
    idempotency_key, retry_count, last_error, delivered_at, created_at, updated_at
`

type UpdateReminderSQLParams struct {
	ApplicationID *string    `json:"application_id"`
	ContactID     *string    `json:"contact_id"`
	Title         *string    `json:"title"`
	Description   *string    `json:"description"`
	DueAt         *time.Time `json:"due_at"`
	ID            string     `json:"id"`
}

type UpdateReminderSQLRow struct {
	ID             string             `json:"id"`
	ApplicationID  string             `json:"application_id"`
	ContactID      interface{}        `json:"contact_id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	RetryCount     int32              `json:"retry_count"`
	LastError      *string            `json:"last_error"`
	DeliveredAt    *time.Time         `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateReminderSQL(ctx context.Context, arg UpdateReminderSQLParams) (UpdateReminderSQLRow, error) {
	row := q.db.QueryRow(ctx, updateReminderSQL,
		arg.ApplicationID,
		arg.ContactID,
		arg.Title,
		arg.Description,
		arg.DueAt,
		arg.ID,
	)
	var i UpdateReminderSQLRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ContactID,
		&i.Title,
		&i.Description,
		&i.DueAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.RetryCount,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReminderStatusSQL = `-- name: UpdateReminderStatusSQL :one
UPDATE reminders
SET status = $1, updated_at = now()
WHERE id = $2::uuid
RETURNING id::text, application_id::text, COALESCE(contact_id::text, '') AS contact_id, title, description, due_at, status,
    idempotency_key, retry_count, last_error, delivered_at, created_at, updated_at
`

type UpdateReminderStatusSQLParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

type UpdateReminderStatusSQLRow struct {
	ID             string             `json:"id"`
	ApplicationID  string             `json:"application_id"`
	ContactID      interface{}        `json:"contact_id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	RetryCount     int32              `json:"retry_count"`
	LastError      *string            `json:"last_error"`
	DeliveredAt    *time.Time         `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateReminderStatusSQL(ctx context.Context, arg UpdateReminderStatusSQLParams) (UpdateReminderStatusSQLRow, error) {
	row := q.db.QueryRow(ctx, updateReminderStatusSQL, arg.Status, arg.ID)
	var i UpdateReminderStatusSQLRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ContactID,
		&i.Title,
		&i.Description,
		&i.DueAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.RetryCount,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
