import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import type { PoolClient } from "pg";

const migrationFilePattern = /^(\d+)_([^.]+)\.sql$/;
const upMarker = /^-- \+goose Up\s*$/m;
const downMarker = /^-- \+goose Down\s*$/m;

export interface Migration {
  version: bigint;
  name: string;
  filePath: string;
  up: string;
  down: string;
}

export interface MigrationStatus {
  migration: Migration;
  applied: boolean;
}

export async function loadMigrations(directory: string): Promise<Migration[]> {
  const fileNames = await readdir(directory);
  const migrations = await Promise.all(
    fileNames
      .filter((name) => migrationFilePattern.test(name))
      .map(async (name) => {
        const match = migrationFilePattern.exec(name);
        if (!match?.[1] || !match[2])
          throw new Error(`invalid migration name: ${name}`);
        const filePath = path.join(directory, name);
        const contents = await readFile(filePath, "utf8");
        const sections = parseMigration(contents, name);
        return {
          version: BigInt(match[1]),
          name: match[2],
          filePath,
          ...sections,
        };
      }),
  );
  return migrations.sort((left, right) =>
    left.version < right.version ? -1 : left.version > right.version ? 1 : 0,
  );
}

export function parseMigration(
  contents: string,
  name = "migration",
): Pick<Migration, "up" | "down"> {
  const up = upMarker.exec(contents);
  const down = downMarker.exec(contents);
  if (!up || !down || down.index <= up.index)
    throw new Error(`${name} must contain ordered goose Up and Down sections`);
  const upSql = contents.slice(up.index + up[0].length, down.index).trim();
  const downSql = contents.slice(down.index + down[0].length).trim();
  if (!upSql || !downSql)
    throw new Error(`${name} must contain non-empty Up and Down SQL`);
  return { up: upSql, down: downSql };
}

export async function migrateUp(
  client: PoolClient,
  migrations: Migration[],
): Promise<Migration[]> {
  const states = await currentStates(client);
  const current = highestAppliedVersion(states);
  const pending = migrations.filter(
    ({ version }) => states.get(version.toString()) !== true,
  );
  const outOfOrder = pending.find(({ version }) => version < current);
  if (outOfOrder)
    throw new Error(
      `database is missing migration ${outOfOrder.version.toString()} below current version ${current.toString()}`,
    );
  for (const migration of pending) await apply(client, migration, true);
  return pending;
}

export async function migrateDown(
  client: PoolClient,
  migrations: Migration[],
): Promise<Migration | null> {
  const states = await currentStates(client);
  const current = highestAppliedVersion(states);
  if (current === 0n) return null;
  const migration = migrations.find(({ version }) => version === current);
  if (!migration)
    throw new Error(
      `migration file for current version ${current.toString()} is missing`,
    );
  await apply(client, migration, false);
  return migration;
}

export async function migrationStatus(
  client: PoolClient,
  migrations: Migration[],
): Promise<MigrationStatus[]> {
  const states = await currentStates(client);
  return migrations.map((migration) => ({
    migration,
    applied: states.get(migration.version.toString()) === true,
  }));
}

export async function prepareMigrationDatabase(
  client: PoolClient,
): Promise<void> {
  await client.query(`CREATE TABLE IF NOT EXISTS goose_db_version (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL,
    is_applied BOOLEAN NOT NULL,
    tstamp TIMESTAMP NOT NULL DEFAULT now()
  )`);
  const initial = await client.query(
    "SELECT 1 FROM goose_db_version WHERE version_id = 0 LIMIT 1",
  );
  if (initial.rowCount === 0)
    await client.query(
      "INSERT INTO goose_db_version (version_id, is_applied) VALUES (0, true)",
    );
}

async function currentStates(
  client: PoolClient,
): Promise<Map<string, boolean>> {
  const result = await client.query<{
    version_id: string;
    is_applied: boolean;
  }>(
    `SELECT DISTINCT ON (version_id) version_id::text, is_applied
     FROM goose_db_version
     ORDER BY version_id, id DESC`,
  );
  return new Map(
    result.rows.map(({ version_id, is_applied }) => [version_id, is_applied]),
  );
}

function highestAppliedVersion(states: Map<string, boolean>): bigint {
  let highest = 0n;
  for (const [version, applied] of states) {
    const parsed = BigInt(version);
    if (applied && parsed > highest) highest = parsed;
  }
  return highest;
}

async function apply(
  client: PoolClient,
  migration: Migration,
  up: boolean,
): Promise<void> {
  await client.query("BEGIN");
  try {
    await client.query(up ? migration.up : migration.down);
    await client.query(
      "INSERT INTO goose_db_version (version_id, is_applied) VALUES ($1, $2)",
      [migration.version.toString(), up],
    );
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  }
}
